### ISSUE TITLE
Linux: if I change my terminal shortcuts sendcode stops working

### ISSUE THREAD

**Issue by CNuge** [randy3k/SendCode#118]
I was playing around with my terminal shortcuts and switched the copy and paste shortcuts from `ctrl-shift-c` and `ctrl-shift-v` to `ctrl-c` and `ctrl-v` respectively in order to make functionality more like mac and pc. When I did this SendCode was no longer able to send commands to the terminal.

Would it be possible to make the linux version accommodate both `ctrl-shift-v` and `ctrl-v` terminal paste commands? I would like to be able to remap my shortcuts but also maintain SendCode functionality.

**Comment by randy3k** [comment]
It is not possible at the moment. The relevant code is
https://github.com/randy3k/SendCode/blob/2712ba6dd3f279eca3892b5f354d9644193b502e/code_sender/linux/__init__.py#L33
We would make this customizable.

In theory, you could change it to anything. However, keep in mind that if you use `ctrl + enter` to send text, you would be holding the `ctrl` key. The `paste` command should use the `ctrl` modifier otherwise SendCode won't work.
