### ISSUE TITLE
SendCode doesn't work

### ISSUE THREAD

**Issue by sjianlyer** [randy3k/SendCode#32]
Hi,
Sublime text and R-Box is my favorite tools for r coding. Thanks for what you did! But since the 'SendTextPlus' package was replaced by 'SendCode', I found 'SendCode' seems not to open R console automatically. In the past, I always open the SublimeText and pressed [ctrl]+[enter] to execute the first line and open the R console by the way. I checked the 'src/r/__init__.py' and couldn't find any code to open R console, just FindWindow. Am I right? 
I'm not familiar with python. It still didn't work when I add some code like 'os.system()' or 'win32api.ShellExecute()' in the 'src/r/__init__.py' to open R console.
How can I use the 'SendCode' like 'SendTextPlus' as usual? Thanks.

**Comment by randy3k** [comment]
Just to clarify, does SendCode completely not working or it just doesn't open the R program automatically?

Unfortnately, automatically opening R GUI actually creates more problems (for example: to detect the program, to chose between versions, to validate the program exists)...
So I dropped the support of opening R program in the initial version of SendCode. It doesn't mean it will never be supported, it just takes time.....

tw, SendTextPlus is still available from its source, it is just not available from Package Control since it is no longer supported.

**Comment by sjianlyer** [comment]
Sorry for making confusion. SendCode worked well when I open the R program manually. It just cann't open R automatically. Actually, it's not inconvenient. I'm just not sure whether I did the wrong way. Thanks for your explaination.

**Comment by randy3k** [comment]
use #28 to track this.
